## Introduction

In this task, you will interact with a genomic sequencing model that has been cleverly encoded with a hidden message. The model contains lots of secrets that the TrAItor will want to get access to. The best way to to protect our sensitive data is to determine the areas where the model needs improvement. Can you decode the message and reveal the secret it holds?

## Objective

Your objective is to extract the hidden message that the model was trained on. Once you have successfully decoded the message, submit it to receive your well-deserved flag.

**NOTE** Rate Limit requirements.

Please limit endpoint requests to 1 request per second per user. Any excessive requests may result in disqualification from the competition.

## Setup

In order to interact with the challenge, you will need your API Key.

You can find this key in the Crucible platform in this challenge.

[https://crucible.dreadnode.io/challenges/genigma](https://crucible.dreadnode.io/challenges/genigma)

In [3]:
CRUCIBLE_API_KEY = "YOUR_API_KEY"  # Replace with your actual API key
with open('../api.txt', 'r') as f:
    CRUCIBLE_API_KEY = f.readline()

## Required packages

Install the required packages.


In [5]:
%pip install requests

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## Notebook variables

Set the variables used throughout the notebook


In [4]:
CHALLENGE = "genigma"
CRUCIBLE_URL = "https://crucible.dreadnode.io"
CHALLENGE_URL = "https://genigma.crucible.dreadnode.io"

## Hack the Model Endpoint

Use this endpoint to submit genetic data.

In [41]:
import requests
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import time


def query_model(input_data):
    response = requests.post(
        f"{CHALLENGE_URL}/predict",
        headers={"X-API-Key": CRUCIBLE_API_KEY},
        json={"data": input_data},
    )
    return response.json()


Xs = []
Ys = []
for i in range(20):
    print(i)
    time.sleep(1.5)
    input_data = np.random.randint(0, 25, size=(100, 1))
    # zero_to_24 = list(range(0, 100))
    # input_data = np.resize(np.array(zero_to_24), (100, 1))
    response = query_model(input_data.tolist())
    predictions = np.array(response['prediction']) 
    predictions

    X = input_data
    Y = predictions
    Xs.append(X)
    Ys.append(Y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [42]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Assuming you have your data as lists of numpy arrays
# Xs: list of arrays of shape (100, 1)
# Ys: list of arrays of shape (16, 1)

# Stack all X and Y arrays into matrices
X_all = np.hstack(Xs).T  # Shape: (n, 100)
Y_all = np.hstack(Ys).T  # Shape: (n, 16)

# Initialize and fit the linear regression model
model = LinearRegression()
model.fit(X_all, Y_all)

# Get the weight matrix and bias vector
W = model.coef_  # Shape: (16, 100)
b = model.intercept_  # Shape: (16,)

print("Weight matrix W:", W)
print("Bias vector b:", b)


Weight matrix W: [[ 7.34734075e-04 -7.81940826e-06  2.64678097e-04 ... -1.53133010e-04
  -3.35294636e-04 -1.05178855e-04]
 [ 2.57160082e-03  6.45370495e-04  6.33737878e-04 ... -3.59876164e-04
  -8.35503706e-04  4.07878596e-04]
 [ 1.71720135e-03  4.53279509e-04  3.52126772e-04 ... -1.97282014e-04
  -6.25093100e-04  3.37855212e-04]
 ...
 [ 5.62844292e-04  1.81453235e-04  1.45476054e-04 ... -7.80798351e-05
  -1.67254337e-04  5.43712973e-05]
 [ 2.83508178e-03  7.31484619e-04  6.72557475e-04 ... -4.25132886e-04
  -9.30605517e-04  4.34440848e-04]
 [ 1.25871062e-03  3.56964743e-04  2.89429628e-04 ... -1.93596371e-04
  -3.99446536e-04  2.34611515e-04]]
Bias vector b: [0.28634018 0.22008734 0.3052999  0.42305789 0.29960602 0.34641406
 0.33970245 0.50705322 0.36354293 0.390319   0.36196905 0.31403372
 0.30736056 0.33992205 0.22118136 0.32380124]


In [37]:
import numpy as np

# Assuming you have your data as lists of numpy arrays
# Xs: list of arrays of shape (100, 1)
# Ys: list of arrays of shape (16, 1)

# Stack all X and Y arrays into matrices
X_all = np.hstack(Xs)  # Shape: (100, n)
Y_all = np.hstack(Ys)  # Shape: (16, n)
n = X_all.shape[1]  # Number of samples

# Add a row of ones to X_all for the bias term
X_all_with_bias = np.vstack([X_all, np.ones((1, n))])  # Shape: (101, n)

# Solve for W and b using least-squares
W_b, residuals, rank, s = np.linalg.lstsq(X_all_with_bias.T, Y_all.T, rcond=None)
W_b = W_b.T  # Transpose back to get shape (16, 101)

# Separate W and b
W = W_b[:, :-1]  # Shape: (16, 100)
b = W_b[:, -1:]  # Shape: (16, 1)

print("Weight matrix W:", W)
print("Bias vector b:", b)

Weight matrix W: [[0.00020442 0.00025887 0.00028745 ... 0.00029784 0.00026203 0.00025178]
 [0.00020204 0.00026722 0.00033189 ... 0.00030859 0.00027512 0.00025545]
 [0.00025031 0.00025138 0.00034869 ... 0.00035698 0.00034092 0.00029201]
 ...
 [0.00016774 0.00027175 0.00028047 ... 0.00033007 0.00029893 0.00032737]
 [0.0001247  0.00027959 0.0002554  ... 0.00032149 0.000296   0.00035695]
 [0.0002649  0.00030679 0.00034937 ... 0.00032186 0.00032377 0.00029379]]
Bias vector b: [[2.33665200e-05]
 [2.42149128e-05]
 [2.67300280e-05]
 [2.50264609e-05]
 [2.43346357e-05]
 [2.49649478e-05]
 [2.31053514e-05]
 [2.44765683e-05]
 [2.68840483e-05]
 [2.32499811e-05]
 [2.33436987e-05]
 [2.14083076e-05]
 [2.36746292e-05]
 [2.58194280e-05]
 [2.59439507e-05]
 [2.69262171e-05]]


In [38]:
W.shape

(16, 100)

In [8]:
input_data = np.zeros((100, 1))
response = query_model(input_data.tolist())
predictions = np.array(response['prediction']) 
predictions

array([[0.1379411 ],
       [0.14017329],
       [0.18642895],
       [0.16373076],
       [0.13963117],
       [0.16077282],
       [0.13729851],
       [0.13969673],
       [0.18523814],
       [0.13947802],
       [0.13830495],
       [0.13842526],
       [0.13832571],
       [0.16387797],
       [0.16311711],
       [0.18794469]])

In [9]:
input_data = np.ones((100, 1))
response = query_model(input_data.tolist())
predictions = np.array(response['prediction']) 
predictions

array([[0.33871297],
       [0.3448043 ],
       [0.39187548],
       [0.37238342],
       [0.32915496],
       [0.36518559],
       [0.31233823],
       [0.35451477],
       [0.37689225],
       [0.32793761],
       [0.33472062],
       [0.33201235],
       [0.34176591],
       [0.36143492],
       [0.37553736],
       [0.38609485]])

In [61]:
input_data = np.ones((100, 1))
response = query_model(input_data.tolist())
predictions = np.array(response['prediction']) 
predictions

array([[0.33871297],
       [0.3448043 ],
       [0.39187548],
       [0.37238342],
       [0.32915496],
       [0.36518559],
       [0.31233823],
       [0.35451477],
       [0.37689225],
       [0.32793761],
       [0.33472062],
       [0.33201235],
       [0.34176591],
       [0.36143492],
       [0.37553736],
       [0.38609485]])

## Submit Passphrase

Once you've identified the secret message, submit it to this endpoint.

In [6]:
import requests


def query(input_data):
    response = requests.post(
        f"{CHALLENGE_URL}/score",
        headers={"X-API-Key": CRUCIBLE_API_KEY},
        json={"data": input_data},
    )
    return response.json()


response = query("Convolutional ")
print(response)

{'error': 'Invalid passphrase'}


In [7]:
import string
import time

for letter in string.ascii_uppercase + string.ascii_lowercase:
    time.sleep(2)
    response = query(letter)
    print(response)

for letter in range(0, 10):
    time.sleep(2)
    response = query(str(letter))
    print(response)


{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error': 'Invalid passphrase'}
{'error'

## Submit Flag

When you find the answer, you will get a flag back. It will look something like `gAAAAA ...`.
You can submit it using the code below, or, on the challenge page.

In [ ]:
import requests


def submit_flag(flag):
    url = f"{CRUCIBLE_URL}/api/challenges/{CHALLENGE}/submit-flag"
    headers = {"X-API-Key": CRUCIBLE_API_KEY}
    payload = {"challenge": CHALLENGE, "flag": flag}
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 200:
        if response.json().get("correct") is True:
            print("The flag was correct. Congrats!")
        else:
            print("The flag was incorrect. Keep trying!")
    else:
        print("There was an error submitting your flag")
        print(response.text)


FLAG = "gAAAAA..."  # Replace with the flag once you find it
submit_flag(FLAG)